export enum ResumeSection {
    INTRODUCTION = 'INTRODUCTION',
    EXPERIENCE = 'EXPERIENCE',
    SKILLSANDCERTIFICATES = 'SKILLSANDCERTIFICATES',
    EDUCATION = 'EDUCATION',
    PROJECTS = 'PROJECTS'
}